/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/recruitment/subscriptions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 모집 사전 알림 구독 */
    post: operations['subscribe'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/applications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 지원서 제출 */
    post: operations['submitApplication'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/applications/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 지원서 CSV 파일 생성 */
    post: operations['downloadApplications'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 후기 전체 조회
     * @description 트랙/기수 필터링 가능. 기본 정렬은 기수 내림차순.
     */
    get: operations['getReviews'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/{term}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 모집 공고 정보 조회 */
    get: operations['getRecruitment'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 모집 중 여부 조회 */
    get: operations['getRecruitmentStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/questions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 지원서 질문 목록 조회 */
    get: operations['getQuestions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/deadline': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 모집 마감 일시 조회 */
    get: operations['getDeadline'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/curriculums': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 커리큘럼 전체 조회
     * @description 트랙 필터링 가능. 미입력 시 전체 3개 트랙 반환.
     */
    get: operations['getCurriculums'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/archiving/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 프로젝트 아카이빙 목록 조회 */
    get: operations['getProjects'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/archiving/faqs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * FAQ 조회
     * @description 카테고리별 FAQ 목록을 order_num 오름차순으로 반환합니다.
     */
    get: operations['getFaqs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/archiving/blogs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 기술 블로그 아카이빙 조회 */
    get: operations['getBlogs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/archiving/activities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 활동 사진 아카이빙 조회 */
    get: operations['getActivities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SubscriptionRequest: {
      email: string;
    };
    ApiResponseSubscriptionResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['SubscriptionResponse'];
      errorCode?: string;
      message?: string;
    };
    SubscriptionResponse: {
      email?: string;
    };
    AnswerRequest: {
      answer: components['schemas']['JsonNode'];
      question_id: string;
    };
    ApplicationRequest: {
      /** @enum {string} */
      track: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      name: string;
      email: string;
      phone: string;
      university: string;
      major: string;
      answers: components['schemas']['AnswerRequest'][];
      /** Format: int64 */
      recruitment_id: number;
      minor_double_major?: string[];
      /** Format: int32 */
      last_semester: number;
      /** @enum {string} */
      military_status: 'COMPLETED_OR_EXEMPT' | 'NOT_COMPLETED';
      birth_date: string;
      graduation_date: string;
      grad_school_plan: boolean;
    };
    JsonNode: Record<string, never>;
    ApiResponseApplicationResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ApplicationResponse'];
      errorCode?: string;
      message?: string;
    };
    ApplicationResponse: {
      /** Format: int64 */
      applicant_id?: number;
      /** Format: date-time */
      submitted_at?: string;
    };
    ApiResponseVoid: {
      /** Format: int32 */
      status?: number;
      data?: Record<string, never>;
      errorCode?: string;
      message?: string;
    };
    ApiResponseListReviewResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ReviewResponse'][];
      errorCode?: string;
      message?: string;
    };
    ReviewResponse: {
      /**
       * Format: int64
       * @description 후기 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 작성자 이름
       * @example 김분석
       */
      name?: string;
      /**
       * @description 트랙
       * @example ANALYSIS
       * @enum {string}
       */
      track?: 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /**
       * Format: int32
       * @description 기수
       * @example 15
       */
      term?: number;
      /**
       * @description 후기 내용
       * @example BOAZ에서 데이터 분석을 공부하며 정말 많이 성장했습니다. 실전 프로젝트를 통해 이론으로만 알던 머신러닝을 직접 적용해볼 수 있어서 좋았어요.
       */
      content?: string;
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/images/review1.jpg
       */
      image_url?: string;
    };
    ApiResponseRecruitmentResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['RecruitmentResponse'];
      errorCode?: string;
      message?: string;
    };
    RecruitmentResponse: {
      /** Format: int32 */
      term?: number;
      /** Format: date-time */
      startDate?: string;
      /** Format: date-time */
      endDate?: string;
      schedule?: components['schemas']['JsonNode'];
      brochureUrl?: string;
      isActive?: boolean;
    };
    ApiResponseRecruitmentStatusResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['RecruitmentStatusResponse'];
      errorCode?: string;
      message?: string;
    };
    RecruitmentStatusResponse: {
      isActive?: boolean;
      /** Format: int32 */
      term?: number;
    };
    ApiResponseListQuestionResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['QuestionResponse'][];
      errorCode?: string;
      message?: string;
    };
    QuestionResponse: {
      questionId?: string;
      category?: string;
      type?: string;
      content?: string;
      /** Format: int32 */
      limitLength?: number;
      metadata?: components['schemas']['JsonNode'];
      /** Format: int32 */
      orderNum?: number;
      isRequired?: boolean;
    };
    ApiResponseDeadlineResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['DeadlineResponse'];
      errorCode?: string;
      message?: string;
    };
    DeadlineResponse: {
      /** Format: date-time */
      deadline?: string;
      /** Format: int64 */
      recruitment_id?: number;
    };
    ApiResponseListCurriculumResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['CurriculumResponse'][];
      errorCode?: string;
      message?: string;
    };
    CurriculumResponse: {
      /**
       * Format: int64
       * @description 커리큘럼 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 트랙
       * @example ANALYSIS
       * @enum {string}
       */
      track?: 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /** @description 커리큘럼 단계 목록 */
      curriculum_steps?: components['schemas']['CurriculumStepResponse'][];
    };
    CurriculumStepResponse: {
      /**
       * Format: int32
       * @description 단계 번호
       * @example 1
       */
      step?: number;
      /**
       * @description 단계 제목
       * @example 데이터 분석 기초
       */
      title?: string;
      /**
       * @description 단계 설명
       * @example 통계 기초, 파이썬 기초
       */
      desc?: string;
    };
    ApiResponseArchivePageResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ArchivePageResponse'];
      errorCode?: string;
      message?: string;
    };
    ArchiveItemResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: int32 */
      term?: number;
      title?: string;
      teamName?: string;
      /** @enum {string} */
      track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      imageUrl?: string;
      links?: {
        [key: string]: string;
      };
      /** Format: date */
      contentDate?: string;
    };
    ArchivePageResponse: {
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      /** Format: int32 */
      currentSize?: number;
      /** Format: int64 */
      totalSize?: number;
      hasPrevious?: boolean;
      hasNext?: boolean;
      posts?: components['schemas']['ArchiveItemResponse'][];
    };
    ApiResponseListFaqResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['FaqResponse'][];
      errorCode?: string;
      message?: string;
    };
    FaqResponse: {
      /**
       * Format: int64
       * @description FAQ ID
       * @example 1
       */
      id?: number;
      /**
       * @description 질문
       * @example BOAZ에 지원하려면 어떤 조건이 필요한가요?
       */
      question?: string;
      /**
       * @description 답변
       * @example 학부생 및 대학원생이라면 누구나 지원 가능합니다. 전공 제한 없이 데이터에 관심 있는 분이라면 환영합니다.
       */
      answer?: string;
      /**
       * @description 카테고리
       * @example 지원
       * @enum {string}
       */
      category?: 'RECRUITMENT' | 'ACTIVITY' | 'ETC';
      /**
       * Format: int32
       * @description 정렬 순서
       * @example 1
       */
      order_num?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  subscribe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubscriptionRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSubscriptionResponse'];
        };
      };
    };
  };
  submitApplication: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ApplicationRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseApplicationResponse'];
        };
      };
    };
  };
  downloadApplications: {
    parameters: {
      query: {
        term: number;
      };
      header: {
        'X-Admin-Key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  getReviews: {
    parameters: {
      query?: {
        track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
        term?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListReviewResponse'];
        };
      };
    };
  };
  getRecruitment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        term: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRecruitmentResponse'];
        };
      };
    };
  };
  getRecruitmentStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRecruitmentStatusResponse'];
        };
      };
    };
  };
  getQuestions: {
    parameters: {
      query: {
        recruitmentId: number;
        track: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListQuestionResponse'];
        };
      };
    };
  };
  getDeadline: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseDeadlineResponse'];
        };
      };
    };
  };
  getCurriculums: {
    parameters: {
      query?: {
        track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListCurriculumResponse'];
        };
      };
    };
  };
  getProjects: {
    parameters: {
      query?: {
        track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
        term?: number;
        keyword?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseArchivePageResponse'];
        };
      };
    };
  };
  getFaqs: {
    parameters: {
      query: {
        category: 'RECRUITMENT' | 'ACTIVITY' | 'ETC';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListFaqResponse'];
        };
      };
    };
  };
  getBlogs: {
    parameters: {
      query?: {
        track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
        keyword?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseArchivePageResponse'];
        };
      };
    };
  };
  getActivities: {
    parameters: {
      query?: {
        term?: number;
        keyword?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseArchivePageResponse'];
        };
      };
    };
  };
}
