/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/recruitment/{recruitmentId}/applications/draft': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** 지원서 임시저장 */
    put: operations['saveDraft'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/applicants/{applicantId}/evaluations/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 개인 평가 조회
     * @description 로그인한 평가자 본인이 이 지원자에 매긴 평가를 반환합니다. 미평가 시 data=null.
     */
    get: operations['getMyEvaluation'];
    /**
     * 개인 평가 저장 (upsert)
     * @description 로그인한 평가자 본인의 평가를 저장합니다. 본인 부문 지원자만 가능, SUBMITTED만 가능.
     */
    put: operations['saveMyEvaluation'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/curriculums/{curriculumId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 커리큘럼 수정
     * @description 커리큘럼 단계를 전체 교체합니다. 부문 변경 불가.
     */
    put: operations['updateCurriculum'];
    post?: never;
    /**
     * 커리큘럼 삭제
     * @description 커리큘럼을 삭제합니다.
     */
    delete: operations['deleteCurriculum'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/{recruitmentId}/applications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 지원서 제출 */
    post: operations['submitApplication'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/subscriptions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 모집 사전 알림 구독 */
    post: operations['subscribe'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/user/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * User 토큰 재발급
     * @description user_refresh_token 쿠키로 Access Token 재발급
     */
    post: operations['refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/user/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * User 로그아웃
     * @description Refresh Token 무효화 및 쿠키 삭제
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/admin/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 어드민 토큰 갱신
     * @description admin_refresh_token 쿠키로 Access Token 재발급
     */
    post: operations['refresh_1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/admin/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 어드민 로그아웃
     * @description Refresh Token 무효화 및 쿠키 삭제
     */
    post: operations['logout_1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/admin/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 어드민 로그인
     * @description 아이디/비밀번호로 로그인. Access Token 반환 및 Refresh Token 쿠키 설정
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 수료자 후기 등록
     * @description 수료자의 동아리 활동 후기를 등록합니다.
     */
    post: operations['createReview'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모든 모집 공고 조회
     * @description is_active 무관 전체 공고를 term 내림차순으로 반환합니다.
     */
    get: operations['getAllRecruitments'];
    put?: never;
    /**
     * 모집 공고 등록
     * @description 새로운 모집 공고를 등록합니다. 동일 기수 중복 등록 불가.
     */
    post: operations['createRecruitment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/questions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 지원서 질문 등록
     * @description 모집 공고에 지원서 질문을 다건 등록합니다. 하나라도 실패 시 전체 롤백.
     */
    post: operations['createQuestions'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/applications/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 지원서 CSV 파일 생성
     * @description term 공고의 지원서를 부문별 CSV로 생성합니다. decision으로 합격(PASS)/불합격(FAIL)/전체(ALL) 추출 범위를 지정합니다.
     */
    post: operations['downloadApplications'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/faqs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * FAQ 등록
     * @description 카테고리별 FAQ를 등록합니다. 동일 카테고리 내 순서 번호 중복 불가.
     */
    post: operations['createFaq'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/curriculums': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 커리큘럼 등록
     * @description 부문별 커리큘럼을 등록합니다. 동일 부문 중복 등록 불가.
     */
    post: operations['createCurriculum'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/archiving/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 프로젝트 등록
     * @description 프로젝트 데이터와 이미지를 등록합니다.
     */
    post: operations['createProject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/archiving/blogs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 기술블로그 등록
     * @description 기술블로그 데이터와 이미지를 등록합니다.
     */
    post: operations['createBlog'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/archiving/activities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 활동사진 등록
     * @description 활동사진 데이터와 이미지를 등록합니다.
     */
    post: operations['createActivity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 모든 계정 조회 (SUPER only) */
    get: operations['getAccounts'];
    put?: never;
    /**
     * 계정 생성 (SUPER only)
     * @description SUPER 권한만 호출 가능. track은 ALL 제외 ANALYSIS·VISUALIZATION·ENGINEERING만 허용.
     */
    post: operations['createAccount'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/users/promote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 합격자 승격
     * @description 합격자 userIds를 받아 memberType을 MEMBER로 변경하고 지원서 개인정보를 User에 복사한다. 비즈니스 오류가 발생한 userId는 skip하고 failedUserIds에 포함하여 반환한다.
     */
    patch: operations['promoteUsers'];
    trace?: never;
  };
  '/api/v1/admin/reviews/{reviewId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 수료자 후기 삭제
     * @description 등록된 수료자 후기를 삭제합니다.
     */
    delete: operations['deleteReview'];
    options?: never;
    head?: never;
    /**
     * 수료자 후기 수정
     * @description 등록된 수료자 후기를 부분 수정합니다. (PATCH)
     */
    patch: operations['updateReview'];
    trace?: never;
  };
  '/api/v1/admin/recruitment/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 모집 공고 삭제
     * @description 특정 모집 공고를 삭제합니다. 연관 데이터(지원자, 질문) 존재 시 삭제 불가.
     */
    delete: operations['deleteRecruitment'];
    options?: never;
    head?: never;
    /**
     * 모집 공고 수정
     * @description 특정 모집 공고를 부분 수정합니다. schedule 수정 시 배열 전체 교체.
     */
    patch: operations['updateRecruitment'];
    trace?: never;
  };
  '/api/v1/admin/recruitment/questions/{questionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 지원서 질문 삭제
     * @description 등록된 지원서 질문을 삭제합니다. 참조 답변 데이터 존재 시 삭제 불가.
     */
    delete: operations['deleteQuestion'];
    options?: never;
    head?: never;
    /**
     * 지원서 질문 수정
     * @description 등록된 지원서 질문을 부분 수정합니다. type 변경 시 연관 필드 함께 처리.
     */
    patch: operations['updateQuestion'];
    trace?: never;
  };
  '/api/v1/admin/recruitment/applicants/{applicantId}/final-decision': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 최종 평가 수정 (대표진 전용)
     * @description 현재 대표진 또는 차기대표진(role=SUPER)만 지원자의 최종 평가(final_decision)를 수정합니다. 현재 대표진은 본인 부문만, 차기대표진은 전 부문.
     */
    patch: operations['updateFinalDecision'];
    trace?: never;
  };
  '/api/v1/admin/faqs/{faqId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * FAQ 삭제
     * @description 등록된 FAQ를 삭제합니다.
     */
    delete: operations['deleteFaq'];
    options?: never;
    head?: never;
    /**
     * FAQ 수정
     * @description 등록된 FAQ를 부분 수정합니다. (PATCH)
     */
    patch: operations['updateFaq'];
    trace?: never;
  };
  '/api/v1/admin/archiving/projects/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 프로젝트 삭제
     * @description 프로젝트 데이터를 삭제합니다.
     */
    delete: operations['deleteProject'];
    options?: never;
    head?: never;
    /**
     * 프로젝트 수정
     * @description 프로젝트 데이터를 수정합니다.
     */
    patch: operations['updateProject'];
    trace?: never;
  };
  '/api/v1/admin/archiving/blogs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 기술블로그 삭제
     * @description 기술블로그 데이터를 삭제합니다.
     */
    delete: operations['deleteBlog'];
    options?: never;
    head?: never;
    /**
     * 기술블로그 수정
     * @description 기술블로그 데이터를 수정합니다.
     */
    patch: operations['updateBlog'];
    trace?: never;
  };
  '/api/v1/admin/archiving/activities/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 활동사진 삭제
     * @description 활동사진 데이터를 삭제합니다.
     */
    delete: operations['deleteActivity'];
    options?: never;
    head?: never;
    /**
     * 활동사진 수정
     * @description 활동사진 데이터를 수정합니다.
     */
    patch: operations['updateActivity'];
    trace?: never;
  };
  '/api/v1/admin/accounts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** id별 계정 조회 (SUPER: 전체 / TEAM: 본인만) */
    get: operations['getAccount'];
    put?: never;
    post?: never;
    /**
     * id별 계정 삭제 (SUPER: 전체 / TEAM: 본인만)
     * @description soft delete. 마지막 SUPER 계정은 삭제 불가. 삭제 시 RefreshToken도 함께 삭제.
     */
    delete: operations['deleteAccount'];
    options?: never;
    head?: never;
    /**
     * id별 계정 수정 (SUPER: role 포함 전체 / TEAM: 본인 프로필만)
     * @description 모든 필드 선택적. role 변경 시 해당 계정의 RefreshToken 삭제(재로그인 강제). 본인 role 변경 불가.
     */
    patch: operations['updateAccount'];
    trace?: never;
  };
  '/api/v1/admin/accounts/{id}/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 비밀번호 변경 (SUPER: 전체 초기화 / TEAM: 본인만)
     * @description 본인 비밀번호 변경 시 currentPassword 필수 (역할 무관). SUPER의 타인 초기화 시 currentPassword 불필요. 변경 후 해당 계정의 RefreshToken 삭제(재로그인 강제).
     */
    patch: operations['resetPassword'];
    trace?: never;
  };
  '/api/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 정보 조회
     * @description 로그인한 사용자의 닉네임 조회
     */
    get: operations['getMyInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 후기 전체 조회
     * @description 부문/기수 필터링 가능. 기본 정렬은 기수 내림차순.
     */
    get: operations['getReviews'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/{term}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 모집 공고 정보 조회 */
    get: operations['getRecruitment'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/{recruitmentId}/applications/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 내 지원서 조회 */
    get: operations['getMyApplication'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 모집 중 여부 조회 */
    get: operations['getRecruitmentStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/questions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 지원서 질문 목록 조회 */
    get: operations['getQuestions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/recruitment/deadline': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 모집 마감 일시 조회 */
    get: operations['getDeadline'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/curriculums': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 커리큘럼 전체 조회
     * @description 부문 필터링 가능. 미입력 시 전체 3개 부문 반환.
     */
    get: operations['getCurriculums'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/archiving/terms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 아카이빙 기수 목록 조회
     * @description 필터 드롭다운용 기수 목록 반환
     */
    get: operations['getTerms'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/archiving/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 프로젝트 아카이빙 목록 조회
     * @description 트랙, 기수, 제목 기반 필터링. 페이지 단위 반환
     */
    get: operations['getProjects'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/archiving/faqs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * FAQ 조회
     * @description 카테고리별 FAQ 목록을 order_num 오름차순으로 반환합니다.
     */
    get: operations['getFaqs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/archiving/blogs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 기술 블로그 아카이빙 조회
     * @description 트랙, 제목 기반 필터링. 페이지 단위 반환
     */
    get: operations['getBlogs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/archiving/activities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 활동 사진 아카이빙 조회
     * @description 기수, 제목 기반 필터링. 페이지 단위 반환
     */
    get: operations['getActivities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/{recruitmentId}/questions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 지원서 질문 목록 조회
     * @description 특정 모집 공고의 질문 목록을 조회합니다. 모집 중 여부와 무관하게 조회 가능.
     */
    get: operations['getAdminQuestions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/{recruitmentId}/applicants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 전체 지원서 조회 (지원자 대시보드)
     * @description 공고 내 전체 지원서를 반환합니다. DRAFT 포함, 정렬·필터·검색은 프론트에서 처리. 차기대표진은 전 부문, 그 외(현재 대표진 포함)는 본인 부문만 조회.
     */
    get: operations['getApplicants'];
    put?: never;
    post?: never;
    /**
     * 지원서 전체 삭제
     * @description 특정 모집 공고의 지원서를 전체 삭제합니다. 모집 진행 중인 경우 삭제 불가.
     */
    delete: operations['deleteApplicants'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/{recruitmentId}/applicants/evaluations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 전체 지원서 및 평가 조회 (평가 대시보드)
     * @description 공고 내 SUBMITTED 지원서 + 평가 집계(합격/보류/불합 개수·총점) + 최종 평가를 반환합니다. 차기대표진은 전 부문, 그 외(현재 대표진 포함)는 본인 부문만 조회.
     */
    get: operations['getApplicantEvaluations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/subscriptions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모집 사전 알림 신청 목록 조회
     * @description 모든 사전 알림 신청 목록을 최신순으로 반환합니다.
     */
    get: operations['getAllSubscriptions'];
    put?: never;
    post?: never;
    /**
     * 모집 사전 알림 신청 전체 삭제
     * @description 모든 사전 알림 신청 데이터를 삭제합니다. 데이터가 없어도 200을 반환합니다.
     */
    delete: operations['deleteAllSubscriptions'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/applicants/{applicantId}/interview-questions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 지원서별 면접 질문 조회
     * @description 한 지원자에 대한 해당 부문 평가자별 면접 질문을 반환합니다. 미작성 평가자는 null로 포함. 차기대표진 외(현재 대표진 포함)에는 본인 부문 지원자만 조회.
     */
    get: operations['getApplicantInterviewQuestions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/applicants/{applicantId}/evaluations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 지원서별 평가 조회
     * @description 한 지원자에 대한 해당 부문 평가자 전체의 평가를 반환합니다. 미평가 평가자는 null로 포함. 차기대표진 외(현재 대표진 포함)에는 본인 부문 지원자만 조회.
     */
    get: operations['getApplicantEvaluators'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/recruitment/applicants/{applicantId}/answers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 지원서 답변 조회
     * @description 한 지원자가 작성한 문항별 답변을 문항 정보(질문 내용·유형)와 함께 문항 순서대로 반환합니다. (평가 사이드바 지원서 본문) 차기대표진 외(현재 대표진 포함)에는 본인 부문 지원자만 조회.
     */
    get: operations['getApplicantAnswers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/accounts/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 계정 정보 조회
     * @description 인증된 본인의 id, 소속, 이름을 반환.
     */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description 답변 목록. null이면 기존 answers 유지, 빈 배열이면 전체 삭제 */
    AnswerRequest: {
      answer: components['schemas']['JsonNode'];
      /**
       * Format: int64
       * @description 질문 ID
       * @example 1
       */
      question_id: number;
    };
    DraftApplicationRequest: {
      /**
       * @description 지원 부문
       * @example ENGINEERING
       * @enum {string}
       */
      track?:
        | 'ALL'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING';
      /**
       * @description 성명
       * @example 홍길동
       */
      name?: string;
      /**
       * @description 이메일
       * @example hong@example.com
       */
      email?: string;
      /**
       * @description 전화번호 (하이픈 없이 숫자만, 10~11자리)
       * @example 01012345678
       */
      phone?: string;
      /**
       * @description 대학교
       * @example 한국대학교
       */
      university?: string;
      /**
       * @description 본전공
       * @example 컴퓨터공학
       */
      major?: string;
      /** @description 답변 목록. null이면 기존 answers 유지, 빈 배열이면 전체 삭제 */
      answers?: components['schemas']['AnswerRequest'][];
      /**
       * @description 부전공/복수전공 목록
       * @example [
       *       "통계학"
       *     ]
       */
      minor_double_major?: string[];
      /**
       * Format: int32
       * @description 마지막 재학 학기
       * @example 4
       */
      last_semester?: number;
      /**
       * @description 병역 상태
       * @enum {string}
       */
      military_status?:
        | 'COMPLETED_OR_EXEMPT'
        | 'NOT_COMPLETED'
        | 'COMPLETED_OR_EXEMPT'
        | 'NOT_COMPLETED';
      /**
       * @description 생년월일 (YYYY-MM-DD)
       * @example 2000-01-01
       */
      birth_date?: string;
      /**
       * @description 졸업 예정 시점
       * @example 2026-02
       */
      graduation_date?: string;
      /**
       * @description 대학원 진학 여부
       * @example false
       */
      grad_school_plan?: boolean;
    };
    /** @description 답변 */
    JsonNode: unknown;
    ApiResponseDraftApplicationResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['DraftApplicationResponse'];
      error_code?: string;
      message?: string;
    };
    DraftApplicationResponse: {
      /**
       * Format: int64
       * @description 지원자 ID
       * @example 42
       */
      applicant_id?: number;
    };
    EvaluationSaveRequest: {
      /** @enum {string} */
      decision: 'PASS' | 'FAIL' | 'HOLD' | 'PENDING';
      /** Format: int32 */
      score?: number;
      memo?: string;
      interview_question?: string;
    };
    ApiResponseMyEvaluationResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['MyEvaluationResponse'];
      error_code?: string;
      message?: string;
    };
    MyEvaluationResponse: {
      /** Format: int64 */
      evaluation_id?: number;
      /** Format: int64 */
      applicant_id?: number;
      /** @enum {string} */
      decision?: 'PASS' | 'FAIL' | 'HOLD' | 'PENDING';
      /** Format: int32 */
      score?: number;
      memo?: string;
      interview_question?: string;
    };
    /** @description 커리큘럼 단계 목록 (전체 교체) */
    CurriculumStepRequest: {
      /**
       * Format: int32
       * @description 단계 번호
       * @example 1
       */
      step: number;
      /**
       * @description 단계 제목
       * @example 데이터 분석 기초
       */
      title: string;
      /**
       * @description 단계 설명
       * @example 통계 기초, 파이썬 기초
       */
      desc: string;
    };
    CurriculumUpdateRequest: {
      /** @description 커리큘럼 단계 목록 (전체 교체) */
      curriculum_steps: components['schemas']['CurriculumStepRequest'][];
    };
    ApiResponseCurriculumResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['CurriculumResponse'];
      error_code?: string;
      message?: string;
    };
    CurriculumResponse: {
      /**
       * Format: int64
       * @description 커리큘럼 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 부문
       * @example ANALYSIS
       * @enum {string}
       */
      track?: 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /** @description 커리큘럼 단계 목록 */
      curriculum_steps?: components['schemas']['CurriculumStepResponse'][];
    };
    /** @description 커리큘럼 단계 목록 */
    CurriculumStepResponse: {
      /**
       * Format: int32
       * @description 단계 번호
       * @example 1
       */
      step?: number;
      /**
       * @description 단계 제목
       * @example 데이터 분석 기초
       */
      title?: string;
      /**
       * @description 단계 설명
       * @example 통계 기초, 파이썬 기초
       */
      desc?: string;
    };
    ApplicationRequest: {
      /**
       * @description 지원 부문
       * @example ENGINEERING
       * @enum {string}
       */
      track:
        | 'ALL'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING';
      /**
       * @description 성명
       * @example 홍길동
       */
      name: string;
      /**
       * @description 이메일
       * @example hong@example.com
       */
      email: string;
      /**
       * @description 전화번호
       * @example 01012345678
       */
      phone: string;
      /**
       * @description 대학교
       * @example 한국대학교
       */
      university: string;
      /**
       * @description 본전공
       * @example 컴퓨터공학
       */
      major: string;
      /** @description 지원서 답변 목록 */
      answers: components['schemas']['AnswerRequest'][];
      /**
       * @description 부전공/복수전공 목록
       * @example [
       *       "통계학"
       *     ]
       */
      minor_double_major?: string[];
      /**
       * Format: int32
       * @description 마지막 재학 학기
       * @example 4
       */
      last_semester: number;
      /**
       * @description 병역 상태
       * @example COMPLETED_OR_EXEMPT
       * @enum {string}
       */
      military_status:
        | 'COMPLETED_OR_EXEMPT'
        | 'NOT_COMPLETED'
        | 'COMPLETED_OR_EXEMPT'
        | 'NOT_COMPLETED';
      /**
       * @description 생년월일
       * @example 2000-01-01
       */
      birth_date: string;
      /**
       * @description 졸업 예정 시점
       * @example 2025-02
       */
      graduation_date: string;
      /**
       * @description 대학원 진학 여부
       * @example false
       */
      grad_school_plan: boolean;
    };
    ApiResponseApplicationResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ApplicationResponse'];
      error_code?: string;
      message?: string;
    };
    ApplicationResponse: {
      /**
       * Format: int64
       * @description 지원자 ID
       * @example 1
       */
      applicant_id?: number;
      /**
       * Format: date-time
       * @description 제출 일시
       */
      submitted_at?: string;
    };
    SubscriptionRequest: {
      /**
       * @description 이메일
       * @example hong@example.com
       */
      email: string;
    };
    ApiResponseSubscriptionResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['SubscriptionResponse'];
      error_code?: string;
      message?: string;
    };
    SubscriptionResponse: {
      /**
       * Format: int64
       * @description 구독 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 구독 이메일
       * @example hong@example.com
       */
      email?: string;
      /**
       * Format: date-time
       * @description 신청 일시
       */
      created_at?: string;
    };
    ApiResponseTokenRefreshResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['TokenRefreshResponse'];
      error_code?: string;
      message?: string;
    };
    TokenRefreshResponse: {
      /**
       * @description Access Token
       * @example eyJhbGciOiJIUzI1NiJ9..
       */
      access_token?: string;
    };
    ApiResponseVoid: {
      /** Format: int32 */
      status?: number;
      data?: Record<string, never>;
      error_code?: string;
      message?: string;
    };
    LoginRequest: {
      /**
       * @description 로그인 ID
       * @example boaz_super
       */
      username: string;
      /**
       * @description 비밀번호
       * @example Boaz1234!
       */
      password: string;
    };
    ApiResponseLoginResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['LoginResponse'];
      error_code?: string;
      message?: string;
    };
    LoginResponse: {
      /**
       * @description Access Token
       * @example eyJhbGciOiJIUzI1NiJ9..
       */
      access_token?: string;
    };
    ReviewCreateRequest: {
      /**
       * @description 작성자 이름
       * @example 김분석
       */
      name: string;
      /**
       * @description 부문
       * @example ANALYSIS
       * @enum {string}
       */
      track:
        | 'ALL'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING';
      /**
       * Format: int32
       * @description 기수
       * @example 15
       */
      term: number;
      /**
       * @description 후기 내용
       * @example BOAZ에서 많이 성장했습니다.
       */
      content: string;
      /**
       * @description 프로필 이미지 URL (선택)
       * @example https://example.com/image.jpg
       */
      image_url?: string;
    };
    ApiResponseReviewResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ReviewResponse'];
      error_code?: string;
      message?: string;
    };
    ReviewResponse: {
      /**
       * Format: int64
       * @description 후기 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 작성자 이름
       * @example 김분석
       */
      name?: string;
      /**
       * @description 부문
       * @example ANALYSIS
       * @enum {string}
       */
      track?: 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /**
       * Format: int32
       * @description 기수
       * @example 15
       */
      term?: number;
      /**
       * @description 후기 내용
       * @example BOAZ에서 데이터 분석을 공부하며 정말 많이 성장했습니다. 실전 프로젝트를 통해 이론으로만 알던 머신러닝을 직접 적용해볼 수 있어서 좋았어요.
       */
      content?: string;
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/images/review1.jpg
       */
      image_url?: string;
    };
    /** @description 모집 일정 목록 */
    ArrayNode: unknown;
    RecruitmentCreateRequest: {
      /**
       * Format: int32
       * @description 모집 기수
       * @example 28
       */
      term: number;
      /**
       * Format: date-time
       * @description 모집 시작 일시
       */
      start_date: string;
      /**
       * Format: date-time
       * @description 모집 종료 일시
       */
      end_date: string;
      schedule: components['schemas']['ArrayNode'];
      /**
       * @description 홍보 책자 링크
       * @example https://example.com/brochure.pdf
       */
      brochure_url?: string;
    };
    ApiResponseRecruitmentIdResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['RecruitmentIdResponse'];
      error_code?: string;
      message?: string;
    };
    RecruitmentIdResponse: {
      /**
       * Format: int64
       * @description 모집 공고 ID
       * @example 12
       */
      recruitment_id?: number;
    };
    /** @description 등록할 질문 목록 */
    QuestionItemRequest: {
      /**
       * @description 파일 내보내기용 column명
       * @example 공통1
       */
      label: string;
      /**
       * @description 질문 카테고리
       * @example COMMON
       * @enum {string}
       */
      category:
        | 'COMMON'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING'
        | 'COMMON'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING';
      /**
       * @description 질문 타입
       * @example TEXT
       * @enum {string}
       */
      type: 'TEXT' | 'TABLE' | 'TEXT' | 'TABLE';
      /**
       * @description 질문 내용
       * @example 자기소개와 BOAZ에 지원한 동기를 서술해주세요.
       */
      content: string;
      /**
       * @description 질문 보조 설명 (선택)
       * @example 면접은 대면으로 진행될 예정입니다.
       */
      description?: string;
      /**
       * Format: int32
       * @description 답변 최대 글자 수 (type=TEXT일 때 필수)
       * @example 500
       */
      limit_length?: number;
      metadata?: components['schemas']['JsonNode'];
      /**
       * Format: int32
       * @description 출력 순서
       * @example 1
       */
      order_num: number;
      /**
       * @description 필수 여부
       * @example true
       */
      is_required: boolean;
    };
    QuestionsCreateRequest: {
      /**
       * Format: int64
       * @description 모집 공고 ID
       * @example 12
       */
      recruitment_id: number;
      /** @description 등록할 질문 목록 */
      questions: components['schemas']['QuestionItemRequest'][];
    };
    ApiResponseQuestionIdsResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['QuestionIdsResponse'];
      error_code?: string;
      message?: string;
    };
    QuestionIdsResponse: {
      /**
       * @description 생성된 질문 ID 목록
       * @example [
       *       1,
       *       2,
       *       3
       *     ]
       */
      ids?: number[];
    };
    FaqCreateRequest: {
      /**
       * @description 질문
       * @example BOAZ에 지원하려면 어떤 조건이 필요한가요?
       */
      question: string;
      /**
       * @description 답변
       * @example 학부생 및 대학원생이라면 누구나 지원 가능합니다.
       */
      answer: string;
      /**
       * @description 카테고리
       * @example RECRUITMENT
       * @enum {string}
       */
      category: 'RECRUITMENT' | 'ACTIVITY' | 'ETC' | 'RECRUITMENT' | 'ACTIVITY' | 'ETC';
      /**
       * Format: int32
       * @description 정렬 순서
       * @example 1
       */
      order_num: number;
    };
    ApiResponseFaqResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['FaqResponse'];
      error_code?: string;
      message?: string;
    };
    FaqResponse: {
      /**
       * Format: int64
       * @description FAQ ID
       * @example 1
       */
      id?: number;
      /**
       * @description 질문
       * @example BOAZ에 지원하려면 어떤 조건이 필요한가요?
       */
      question?: string;
      /**
       * @description 답변
       * @example 학부생 및 대학원생이라면 누구나 지원 가능합니다. 전공 제한 없이 데이터에 관심 있는 분이라면 환영합니다.
       */
      answer?: string;
      /**
       * @description 카테고리
       * @example 지원
       * @enum {string}
       */
      category?: 'RECRUITMENT' | 'ACTIVITY' | 'ETC';
      /**
       * Format: int32
       * @description 정렬 순서
       * @example 1
       */
      order_num?: number;
    };
    CurriculumCreateRequest: {
      /**
       * @description 부문
       * @example ANALYSIS
       * @enum {string}
       */
      track:
        | 'ALL'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING';
      /** @description 커리큘럼 단계 목록 */
      curriculum_steps: components['schemas']['CurriculumStepRequest'][];
    };
    ArchiveCreateRequest: {
      /**
       * Format: int32
       * @description 기수
       * @example 8
       */
      term: number;
      /**
       * @description 제목
       * @example AI 기반 수요 예측 프로젝트
       */
      title: string;
      /**
       * @description 팀명
       * @example 팀이름
       */
      team_name?: string;
      /**
       * @description 트랙
       * @example ANALYSIS
       * @enum {string}
       */
      track: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /**
       * @description 링크 JSON
       * @example {"slideshare":"https://slideshare.net/boaz.com"}
       */
      links: string;
      /**
       * Format: date
       * @description 콘텐츠 날짜
       * @example 2024-07-01
       */
      content_date: string;
      /**
       * @description 상/하반기 (활동사진만 사용)
       * @example 26-1
       */
      half?: string;
    };
    AdminCreateRequest: {
      /**
       * @description 로그인 ID
       * @example boaz_team2
       */
      username: string;
      /**
       * @description 비밀번호 (8자 이상, 영문+숫자+특수문자 포함)
       * @example Boaz1234!
       */
      password: string;
      /**
       * @description 역할
       * @example TEAM
       * @enum {string}
       */
      role: 'SUPER' | 'TEAM' | 'SUPER' | 'TEAM';
      /**
       * @description 이름
       * @example 김보아즈
       */
      name: string;
      /**
       * @description 부문 (ALL 제외)
       * @example ANALYSIS
       * @enum {string}
       */
      track:
        | 'ALL'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING';
      /**
       * Format: int32
       * @description 기수
       * @example 25
       */
      term: number;
      /**
       * @description 직책/소속
       * @example 서비스운영팀
       * @enum {string}
       */
      team_name:
        | '대표진'
        | '차기대표진'
        | '디자인팀'
        | '자료연구팀'
        | '운영지원팀'
        | '기획팀'
        | '대외협력팀'
        | '서비스운영팀'
        | '대표진'
        | '차기대표진'
        | '디자인팀'
        | '자료연구팀'
        | '운영지원팀'
        | '기획팀'
        | '대외협력팀'
        | '서비스운영팀';
    };
    AdminIdResponse: {
      /**
       * Format: int64
       * @description 계정 ID
       * @example 1
       */
      id?: number;
    };
    ApiResponseAdminIdResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['AdminIdResponse'];
      error_code?: string;
      message?: string;
    };
    PromoteUsersRequest: {
      /**
       * @description 승격할 유저 ID 목록
       * @example [
       *       1,
       *       2,
       *       3,
       *       48
       *     ]
       */
      user_ids: number[];
    };
    ApiResponsePromoteUsersResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['PromoteUsersResponse'];
      error_code?: string;
      message?: string;
    };
    /** @description 승격 실패한 유저 ID 목록 및 사유 */
    FailedUserInfo: {
      /**
       * Format: int64
       * @description 유저 ID
       * @example 5
       */
      user_id?: number;
      /**
       * @description 에러 코드
       * @example USER_NOT_FOUND
       */
      error_code?: string;
    };
    PromoteUsersResponse: {
      /** @description 승격 실패한 유저 ID 목록 및 사유 */
      failed_user_ids?: components['schemas']['FailedUserInfo'][];
    };
    ReviewUpdateRequest: {
      /**
       * @description 작성자 이름
       * @example 김분석
       */
      name?: string;
      /**
       * @description 부문
       * @example ANALYSIS
       * @enum {string}
       */
      track?:
        | 'ALL'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING';
      /**
       * Format: int32
       * @description 기수
       * @example 15
       */
      term?: number;
      /**
       * @description 후기 내용
       * @example BOAZ에서 많이 성장했습니다.
       */
      content?: string;
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/image.jpg
       */
      image_url?: string;
    };
    RecruitmentUpdateRequest: {
      /**
       * Format: int32
       * @description 모집 기수
       * @example 28
       */
      term?: number;
      /**
       * Format: date-time
       * @description 모집 시작 일시
       */
      start_date?: string;
      /**
       * Format: date-time
       * @description 모집 종료 일시
       */
      end_date?: string;
      schedule?: components['schemas']['ArrayNode'];
      /**
       * @description 홍보 책자 링크 (null 전송 시 삭제)
       * @example https://example.com/brochure.pdf
       */
      brochure_url?: string;
    };
    QuestionUpdateRequest: {
      /**
       * @description 파일 내보내기용 column명
       * @example 공통1
       */
      label?: string;
      /**
       * @description 질문 카테고리
       * @example COMMON
       * @enum {string}
       */
      category?:
        | 'COMMON'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING'
        | 'COMMON'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING';
      /**
       * @description 질문 타입
       * @example TEXT
       * @enum {string}
       */
      type?: 'TEXT' | 'TABLE' | 'TEXT' | 'TABLE';
      /**
       * @description 질문 내용
       * @example 자기소개와 BOAZ에 지원한 동기를 서술해주세요.
       */
      content?: string;
      /** @description 질문 보조 설명 (null 전송 시 삭제) */
      description?: string;
      /**
       * Format: int32
       * @description 답변 최대 글자 수 (null 전송 시 삭제)
       * @example 500
       */
      limit_length?: number;
      metadata?: components['schemas']['JsonNode'];
      /**
       * Format: int32
       * @description 출력 순서
       * @example 1
       */
      order_num?: number;
      /**
       * @description 필수 여부
       * @example true
       */
      is_required?: boolean;
    };
    ApiResponseQuestionIdResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['QuestionIdResponse'];
      error_code?: string;
      message?: string;
    };
    QuestionIdResponse: {
      /**
       * Format: int64
       * @description 질문 ID
       * @example 1
       */
      question_id?: number;
    };
    FinalDecisionUpdateRequest: {
      /** @enum {string} */
      final_decision: 'PASS' | 'FAIL' | 'HOLD' | 'PENDING';
    };
    ApiResponseFinalDecisionResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['FinalDecisionResponse'];
      error_code?: string;
      message?: string;
    };
    FinalDecisionResponse: {
      /** Format: int64 */
      applicant_id?: number;
      /** @enum {string} */
      final_decision?: 'PASS' | 'FAIL' | 'HOLD' | 'PENDING';
    };
    FaqUpdateRequest: {
      /**
       * @description 질문
       * @example BOAZ에 지원하려면 어떤 조건이 필요한가요?
       */
      question?: string;
      /**
       * @description 답변
       * @example 학부생 및 대학원생이라면 누구나 지원 가능합니다.
       */
      answer?: string;
      /**
       * @description 카테고리
       * @example RECRUITMENT
       * @enum {string}
       */
      category?: 'RECRUITMENT' | 'ACTIVITY' | 'ETC' | 'RECRUITMENT' | 'ACTIVITY' | 'ETC';
      /**
       * Format: int32
       * @description 정렬 순서
       * @example 1
       */
      order_num?: number;
    };
    ArchiveUpdateRequest: {
      /**
       * Format: int32
       * @description 기수
       * @example 8
       */
      term?: number;
      /**
       * @description 제목
       * @example LLM 기반 수요 예측 프로젝트
       */
      title?: string;
      /**
       * @description 팀명
       * @example 보보보아아즈
       */
      team_name?: string;
      /**
       * @description 트랙
       * @example ANALYSIS
       * @enum {string}
       */
      track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /**
       * @description 링크 JSON
       * @example {"slideshare":"https://slideshare.net/bbbaaz.com"}
       */
      links?: string;
      /**
       * Format: date
       * @description 콘텐츠 날짜
       * @example 2024-07-05
       */
      content_date?: string;
      /**
       * @description 상/하반기 (활동사진만 사용)
       * @example 26-1
       */
      half?: string;
    };
    AdminUpdateRequest: {
      /**
       * @description 역할 (SUPER only, 본인 변경 불가)
       * @example TEAM
       * @enum {string}
       */
      role?: 'SUPER' | 'TEAM' | 'SUPER' | 'TEAM';
      /**
       * @description 이름
       * @example 김보아즈
       */
      name?: string;
      /**
       * @description 부문 (ALL 제외)
       * @example ANALYSIS
       * @enum {string}
       */
      track?:
        | 'ALL'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING'
        | 'ANALYSIS'
        | 'VISUALIZATION'
        | 'ENGINEERING';
      /**
       * Format: int32
       * @description 기수
       * @example 25
       */
      term?: number;
      /**
       * @description 직책/소속
       * @example 서비스운영팀
       * @enum {string}
       */
      team_name?:
        | '대표진'
        | '차기대표진'
        | '디자인팀'
        | '자료연구팀'
        | '운영지원팀'
        | '기획팀'
        | '대외협력팀'
        | '서비스운영팀'
        | '대표진'
        | '디자인팀'
        | '자료연구팀'
        | '운영지원팀'
        | '기획팀'
        | '대외협력팀'
        | '서비스운영팀';
    };
    AdminPasswordResetRequest: {
      /**
       * @description 현재 비밀번호 (본인 변경 시 필수, SUPER의 타인 초기화 시 불필요)
       * @example Boaz1234!
       */
      current_password?: string;
      /**
       * @description 새 비밀번호 (8자 이상, 영문+숫자+특수문자 포함)
       * @example NewBoaz1234!
       */
      new_password: string;
    };
    ApiResponseUserInfoResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['UserInfoResponse'];
      error_code?: string;
      message?: string;
    };
    UserInfoResponse: {
      nickname?: string;
    };
    ApiResponseListReviewResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ReviewResponse'][];
      error_code?: string;
      message?: string;
    };
    ApiResponseRecruitmentResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['RecruitmentResponse'];
      error_code?: string;
      message?: string;
    };
    RecruitmentResponse: {
      /**
       * Format: int64
       * @description 모집 공고 ID
       * @example 12
       */
      recruitment_id?: number;
      /**
       * Format: int32
       * @description 기수
       * @example 25
       */
      term?: number;
      /**
       * Format: date-time
       * @description 모집 시작 일시
       */
      start_date?: string;
      /**
       * Format: date-time
       * @description 모집 마감 일시
       */
      end_date?: string;
      schedule?: components['schemas']['JsonNode'];
      /**
       * @description 모집 공고 URL
       * @example https://example.com/brochure
       */
      brochure_url?: string;
      /**
       * @description 모집 중 여부
       * @example true
       */
      is_active?: boolean;
    };
    /** @description 지원서 답변 목록 */
    AnswerItemResponse: {
      /**
       * Format: int64
       * @description 질문 ID
       * @example 1
       */
      question_id?: number;
      answer?: components['schemas']['JsonNode'];
    };
    ApiResponseMyApplicationResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['MyApplicationResponse'];
      error_code?: string;
      message?: string;
    };
    MyApplicationResponse: {
      /**
       * Format: int64
       * @description 지원자 ID
       * @example 42
       */
      applicant_id?: number;
      /**
       * @description 지원서 상태
       * @example DRAFT
       * @enum {string}
       */
      status?: 'DRAFT' | 'SUBMITTED';
      /**
       * @description 지원 부문
       * @example ENGINEERING
       * @enum {string}
       */
      track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /**
       * @description 성명
       * @example 홍길동
       */
      name?: string;
      /**
       * @description 이메일
       * @example hong@example.com
       */
      email?: string;
      /**
       * @description 전화번호
       * @example 01012345678
       */
      phone?: string;
      /**
       * @description 대학교
       * @example 한국대학교
       */
      university?: string;
      /**
       * @description 본전공
       * @example 컴퓨터공학
       */
      major?: string;
      /** @description 부전공/복수전공 목록 */
      minor_double_major?: string[];
      /**
       * Format: int32
       * @description 마지막 재학 학기
       * @example 6
       */
      last_semester?: number;
      /**
       * @description 병역 상태
       * @example COMPLETED_OR_EXEMPT
       * @enum {string}
       */
      military_status?: 'COMPLETED_OR_EXEMPT' | 'NOT_COMPLETED';
      /**
       * Format: date
       * @description 생년월일
       * @example 2000-01-01
       */
      birth_date?: string;
      /**
       * @description 졸업 예정 시점
       * @example 2026-02
       */
      graduation_date?: string;
      /**
       * @description 대학원 진학 여부
       * @example false
       */
      grad_school_plan?: boolean;
      /** @description 지원서 답변 목록 */
      answers?: components['schemas']['AnswerItemResponse'][];
      /**
       * Format: date-time
       * @description 최초 생성 일시
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description 마지막 수정 일시
       */
      updated_at?: string;
    };
    ApiResponseRecruitmentStatusResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['RecruitmentStatusResponse'];
      error_code?: string;
      message?: string;
    };
    RecruitmentStatusResponse: {
      /**
       * @description 모집 중 여부
       * @example true
       */
      is_active?: boolean;
      /**
       * Format: int32
       * @description 현재 모집 기수
       * @example 25
       */
      term?: number;
    };
    ApiResponseListQuestionResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['QuestionResponse'][];
      error_code?: string;
      message?: string;
    };
    QuestionResponse: {
      /**
       * Format: int64
       * @description 질문 ID
       * @example 1
       */
      question_id?: number;
      /**
       * @description 질문 레이블
       * @example 공통1
       */
      label?: string;
      /**
       * @description 카테고리
       * @example COMMON
       * @enum {string}
       */
      category?: 'COMMON' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /**
       * @description 질문 유형
       * @example TEXT
       * @enum {string}
       */
      type?: 'TEXT' | 'TABLE';
      /**
       * @description 질문 내용
       * @example 자신을 소개해주세요.
       */
      content?: string;
      /** @description 질문 보조 설명 */
      description?: string;
      /**
       * Format: int32
       * @description 글자 수 제한 (TEXT 유형인 경우)
       * @example 500
       */
      limit_length?: number;
      metadata?: components['schemas']['JsonNode'];
      /**
       * Format: int32
       * @description 질문 순서
       * @example 1
       */
      order_num?: number;
      /**
       * @description 필수 여부
       * @example true
       */
      is_required?: boolean;
    };
    ApiResponseDeadlineResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['DeadlineResponse'];
      error_code?: string;
      message?: string;
    };
    DeadlineResponse: {
      /**
       * Format: date-time
       * @description 마감 일시
       */
      deadline?: string;
      /**
       * Format: int64
       * @description 모집 ID
       * @example 1
       */
      recruitment_id?: number;
    };
    ApiResponseListCurriculumResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['CurriculumResponse'][];
      error_code?: string;
      message?: string;
    };
    ApiResponseArchiveTermsResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ArchiveTermsResponse'];
      error_code?: string;
      message?: string;
    };
    ArchiveTermsResponse: {
      terms?: components['schemas']['TermItem'][];
    };
    TermItem: {
      /** Format: int32 */
      value?: number;
      label?: string;
    };
    ApiResponseArchivePageResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ArchivePageResponse'];
      error_code?: string;
      message?: string;
    };
    /** @description 아카이브 목록 */
    ArchiveItemResponse: {
      /**
       * Format: int64
       * @description 아카이브 ID
       * @example 1
       */
      id?: number;
      /**
       * Format: int32
       * @description 기수
       * @example 26
       */
      term?: number;
      /**
       * @description 제목
       * @example 실시간 추천 시스템 구축 프로젝트
       */
      title?: string;
      /**
       * @description 팀명
       * @example 팀 보아즈
       */
      team_name?: string;
      /**
       * @description 트랙
       * @example ENGINEERING
       * @enum {string}
       */
      track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /**
       * @description 이미지 URL
       * @example https://boaz-archiving.s3.ap-northeast-2.amazonaws.com/projects/sample.png
       */
      image_url?: string;
      links?: components['schemas']['JsonNode'];
      /**
       * Format: date
       * @description 콘텐츠 날짜
       * @example 2026-04-17
       */
      content_date?: string;
    };
    ArchivePageResponse: {
      /**
       * Format: int32
       * @description 현재 페이지 번호
       * @example 5
       */
      current_page?: number;
      /**
       * Format: int32
       * @description 전체 페이지 수
       * @example 5
       */
      total_pages?: number;
      /**
       * Format: int32
       * @description 페이지당 항목 수
       * @example 6
       */
      size?: number;
      /**
       * Format: int32
       * @description 현재 페이지 항목 수
       * @example 3
       */
      current_size?: number;
      /**
       * Format: int64
       * @description 전체 항목 수
       * @example 33
       */
      total_size?: number;
      /**
       * @description 이전 페이지 존재 여부
       * @example true
       */
      has_previous?: boolean;
      /**
       * @description 다음 페이지 존재 여부
       * @example false
       */
      has_next?: boolean;
      /** @description 아카이브 목록 */
      posts?: components['schemas']['ArchiveItemResponse'][];
    };
    ApiResponseListFaqResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['FaqResponse'][];
      error_code?: string;
      message?: string;
    };
    ApiResponseListRecruitmentResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['RecruitmentResponse'][];
      error_code?: string;
      message?: string;
    };
    ApiResponseListApplicantSummaryResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ApplicantSummaryResponse'][];
      error_code?: string;
      message?: string;
    };
    ApplicantSummaryResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      user_id?: number;
      /** @enum {string} */
      status?: 'DRAFT' | 'SUBMITTED';
      /** @enum {string} */
      track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      name?: string;
      email?: string;
      phone?: string;
      university?: string;
      major?: string;
      minor_double_major?: string[];
      /** Format: int32 */
      last_semester?: number;
      /** @enum {string} */
      military_status?: 'COMPLETED_OR_EXEMPT' | 'NOT_COMPLETED';
      /** Format: date */
      birth_date?: string;
      graduation_date?: string;
      grad_school_plan?: boolean;
      /** Format: date-time */
      submitted_at?: string;
    };
    ApiResponseListApplicantEvaluationResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ApplicantEvaluationResponse'][];
      error_code?: string;
      message?: string;
    };
    ApplicantEvaluationResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      user_id?: number;
      /** @enum {string} */
      track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      name?: string;
      email?: string;
      phone?: string;
      university?: string;
      major?: string;
      minor_double_major?: string[];
      /** Format: int32 */
      last_semester?: number;
      /** @enum {string} */
      military_status?: 'COMPLETED_OR_EXEMPT' | 'NOT_COMPLETED';
      /** Format: date */
      birth_date?: string;
      graduation_date?: string;
      grad_school_plan?: boolean;
      /** Format: date-time */
      submitted_at?: string;
      /** Format: int32 */
      pass_count?: number;
      /** Format: int32 */
      hold_count?: number;
      /** Format: int32 */
      fail_count?: number;
      /** Format: int32 */
      total_score?: number;
      /** @enum {string} */
      final_decision?: 'PASS' | 'FAIL' | 'HOLD' | 'PENDING';
      /** @enum {string} */
      my_decision?: 'PASS' | 'FAIL' | 'HOLD' | 'PENDING';
    };
    ApiResponseListSubscriptionResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['SubscriptionResponse'][];
      error_code?: string;
      message?: string;
    };
    ApiResponseApplicantInterviewQuestionsResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ApplicantInterviewQuestionsResponse'];
      error_code?: string;
      message?: string;
    };
    ApplicantInterviewQuestionsResponse: {
      /** Format: int64 */
      applicant_id?: number;
      interview_questions?: components['schemas']['EvaluatorInterviewQuestionResponse'][];
    };
    EvaluatorInterviewQuestionResponse: {
      /** Format: int64 */
      admin_id?: number;
      name?: string;
      /** @enum {string} */
      track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      interview_question?: string;
    };
    ApiResponseApplicantEvaluatorsResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ApplicantEvaluatorsResponse'];
      error_code?: string;
      message?: string;
    };
    ApplicantEvaluatorsResponse: {
      /** Format: int64 */
      applicant_id?: number;
      evaluations?: components['schemas']['EvaluatorEvaluationResponse'][];
    };
    EvaluatorEvaluationResponse: {
      /** Format: int64 */
      admin_id?: number;
      name?: string;
      /** @enum {string} */
      track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /** @enum {string} */
      decision?: 'PASS' | 'FAIL' | 'HOLD' | 'PENDING';
      /** Format: int32 */
      score?: number;
      memo?: string;
    };
    AnswerDetailResponse: {
      /** Format: int64 */
      question_id?: number;
      label?: string;
      /** @enum {string} */
      category?: 'COMMON' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /** @enum {string} */
      type?: 'TEXT' | 'TABLE';
      content?: string;
      /** Format: int32 */
      order_num?: number;
      answer?: components['schemas']['JsonNode'];
    };
    ApiResponseApplicantAnswersResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['ApplicantAnswersResponse'];
      error_code?: string;
      message?: string;
    };
    ApplicantAnswersResponse: {
      /** Format: int64 */
      applicant_id?: number;
      answers?: components['schemas']['AnswerDetailResponse'][];
    };
    AdminAccountResponse: {
      /**
       * Format: int64
       * @description 계정 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 로그인 ID
       * @example boaz_team2
       */
      username?: string;
      /**
       * @description 역할
       * @example TEAM
       * @enum {string}
       */
      role?: 'SUPER' | 'TEAM';
      /**
       * @description 이름
       * @example 김보아즈
       */
      name?: string;
      /**
       * @description 부문
       * @example ANALYSIS
       * @enum {string}
       */
      track?: 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      /**
       * Format: int32
       * @description 기수
       * @example 25
       */
      term?: number;
      /**
       * @description 직책/소속
       * @example 서비스운영팀
       * @enum {string}
       */
      team_name?:
        | '대표진'
        | '디자인팀'
        | '자료연구팀'
        | '운영지원팀'
        | '기획팀'
        | '대외협력팀'
        | '서비스운영팀';
      /**
       * Format: int64
       * @description 생성한 SUPER 계정 ID
       * @example 1
       */
      created_by?: number;
      /**
       * Format: date-time
       * @description 생성 일시
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description 수정 일시
       */
      updated_at?: string;
    };
    ApiResponseListAdminAccountResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['AdminAccountResponse'][];
      error_code?: string;
      message?: string;
    };
    ApiResponseAdminAccountResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['AdminAccountResponse'];
      error_code?: string;
      message?: string;
    };
    AdminMeResponse: {
      /**
       * Format: int64
       * @description 계정 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 직책/소속
       * @example 대표진
       * @enum {string}
       */
      team_name?:
        | '대표진'
        | '디자인팀'
        | '자료연구팀'
        | '운영지원팀'
        | '기획팀'
        | '대외협력팀'
        | '서비스운영팀';
      /**
       * @description 이름
       * @example 문혁준
       */
      name?: string;
    };
    ApiResponseAdminMeResponse: {
      /** Format: int32 */
      status?: number;
      data?: components['schemas']['AdminMeResponse'];
      error_code?: string;
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  saveDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recruitmentId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DraftApplicationRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseDraftApplicationResponse'];
        };
      };
    };
  };
  getMyEvaluation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        applicantId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMyEvaluationResponse'];
        };
      };
    };
  };
  saveMyEvaluation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        applicantId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EvaluationSaveRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMyEvaluationResponse'];
        };
      };
    };
  };
  updateCurriculum: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculumId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CurriculumUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseCurriculumResponse'];
        };
      };
    };
  };
  deleteCurriculum: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculumId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  submitApplication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recruitmentId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ApplicationRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseApplicationResponse'];
        };
      };
    };
  };
  subscribe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubscriptionRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSubscriptionResponse'];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        user_refresh_token?: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseTokenRefreshResponse'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  refresh_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        admin_refresh_token?: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseTokenRefreshResponse'];
        };
      };
    };
  };
  logout_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseLoginResponse'];
        };
      };
    };
  };
  createReview: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseReviewResponse'];
        };
      };
    };
  };
  getAllRecruitments: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListRecruitmentResponse'];
        };
      };
    };
  };
  createRecruitment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RecruitmentCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRecruitmentIdResponse'];
        };
      };
    };
  };
  createQuestions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QuestionsCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseQuestionIdsResponse'];
        };
      };
    };
  };
  downloadApplications: {
    parameters: {
      query: {
        term: number;
        decision?: 'PASS' | 'FAIL' | 'ALL';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  createFaq: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FaqCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseFaqResponse'];
        };
      };
    };
  };
  createCurriculum: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CurriculumCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseCurriculumResponse'];
        };
      };
    };
  };
  createProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          data?: components['schemas']['ArchiveCreateRequest'];
          /** Format: binary */
          image?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  createBlog: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          data?: components['schemas']['ArchiveCreateRequest'];
          /** Format: binary */
          image?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  createActivity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          data?: components['schemas']['ArchiveCreateRequest'];
          /** Format: binary */
          image?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  getAccounts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListAdminAccountResponse'];
        };
      };
    };
  };
  createAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAdminIdResponse'];
        };
      };
    };
  };
  promoteUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PromoteUsersRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponsePromoteUsersResponse'];
        };
      };
    };
  };
  deleteReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reviewId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reviewId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseReviewResponse'];
        };
      };
    };
  };
  deleteRecruitment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateRecruitment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RecruitmentUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRecruitmentIdResponse'];
        };
      };
    };
  };
  deleteQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QuestionUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseQuestionIdResponse'];
        };
      };
    };
  };
  updateFinalDecision: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        applicantId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FinalDecisionUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseFinalDecisionResponse'];
        };
      };
    };
  };
  deleteFaq: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        faqId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateFaq: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        faqId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FaqUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseFaqResponse'];
        };
      };
    };
  };
  deleteProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          data?: components['schemas']['ArchiveUpdateRequest'];
          /** Format: binary */
          image?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  deleteBlog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateBlog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          data?: components['schemas']['ArchiveUpdateRequest'];
          /** Format: binary */
          image?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  deleteActivity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateActivity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          data?: components['schemas']['ArchiveUpdateRequest'];
          /** Format: binary */
          image?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  getAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAdminAccountResponse'];
        };
      };
    };
  };
  deleteAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  updateAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAdminIdResponse'];
        };
      };
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminPasswordResetRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  getMyInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseUserInfoResponse'];
        };
      };
    };
  };
  getReviews: {
    parameters: {
      query?: {
        track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
        term?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListReviewResponse'];
        };
      };
    };
  };
  getRecruitment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        term: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRecruitmentResponse'];
        };
      };
    };
  };
  getMyApplication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recruitmentId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseMyApplicationResponse'];
        };
      };
    };
  };
  getRecruitmentStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRecruitmentStatusResponse'];
        };
      };
    };
  };
  getQuestions: {
    parameters: {
      query: {
        recruitmentId: number;
        track: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListQuestionResponse'];
        };
      };
    };
  };
  getDeadline: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseDeadlineResponse'];
        };
      };
    };
  };
  getCurriculums: {
    parameters: {
      query?: {
        track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListCurriculumResponse'];
        };
      };
    };
  };
  getTerms: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseArchiveTermsResponse'];
        };
      };
    };
  };
  getProjects: {
    parameters: {
      query?: {
        track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
        term?: number;
        keyword?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseArchivePageResponse'];
        };
      };
    };
  };
  getFaqs: {
    parameters: {
      query: {
        category: 'RECRUITMENT' | 'ACTIVITY' | 'ETC';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListFaqResponse'];
        };
      };
    };
  };
  getBlogs: {
    parameters: {
      query?: {
        track?: 'ALL' | 'ANALYSIS' | 'VISUALIZATION' | 'ENGINEERING';
        keyword?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseArchivePageResponse'];
        };
      };
    };
  };
  getActivities: {
    parameters: {
      query?: {
        term?: number;
        keyword?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseArchivePageResponse'];
        };
      };
    };
  };
  getAdminQuestions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recruitmentId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListQuestionResponse'];
        };
      };
    };
  };
  getApplicants: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recruitmentId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListApplicantSummaryResponse'];
        };
      };
    };
  };
  deleteApplicants: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recruitmentId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  getApplicantEvaluations: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recruitmentId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListApplicantEvaluationResponse'];
        };
      };
    };
  };
  getAllSubscriptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListSubscriptionResponse'];
        };
      };
    };
  };
  deleteAllSubscriptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
    };
  };
  getApplicantInterviewQuestions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        applicantId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseApplicantInterviewQuestionsResponse'];
        };
      };
    };
  };
  getApplicantEvaluators: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        applicantId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseApplicantEvaluatorsResponse'];
        };
      };
    };
  };
  getApplicantAnswers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        applicantId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseApplicantAnswersResponse'];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAdminMeResponse'];
        };
      };
    };
  };
}
