import type { components } from './schema';

export type RecruitmentStatusResponse = components['schemas']['RecruitmentStatusResponse'];
export type RecruitmentResponse = components['schemas']['RecruitmentResponse'];
export type DeadlineResponse = components['schemas']['DeadlineResponse'];
export type QuestionResponse = components['schemas']['QuestionResponse'];
export type ApplicationRequest = components['schemas']['ApplicationRequest'];
export type AnswerRequest = components['schemas']['AnswerRequest'];
export type ApplicationResponse = components['schemas']['ApplicationResponse'];
export type SubscriptionRequest = components['schemas']['SubscriptionRequest'];
export type ReviewResponse = components['schemas']['ReviewResponse'];
export type CurriculumResponse = components['schemas']['CurriculumResponse'];
export type CurriculumStepResponse = components['schemas']['CurriculumStepResponse'];
export type ArchivePageResponse = components['schemas']['ArchivePageResponse'];
export type ArchiveItemResponse = components['schemas']['ArchiveItemResponse'];
export type FaqResponse = components['schemas']['FaqResponse'];
export type Track = Exclude<ApplicationRequest['track'], 'ALL'>;
export type MilitaryStatus = ApplicationRequest['military_status'];
export type DraftRequest = components['schemas']['DraftApplicationRequest'];
export type DraftResponse = components['schemas']['DraftApplicationResponse'];
export type MyApplicationResponse = components['schemas']['MyApplicationResponse'];
export type AnswerItemResponse = components['schemas']['AnswerItemResponse'];
export type ApplicationStatus = NonNullable<MyApplicationResponse['status']>;
